// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6LMWRgw4pmpXOrQezQxUp8omrQImrODc',
    appId: '1:1047486986075:web:6706a57e816a95b61fcc7e',
    messagingSenderId: '1047486986075',
    projectId: 'flutterapps-1b0d5',
    authDomain: 'flutterapps-1b0d5.firebaseapp.com',
    storageBucket: 'flutterapps-1b0d5.appspot.com',
    measurementId: 'G-BXXC1WH8MY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGxJ2Fr7Dbwh_irZzAeUaG_7ZpLdqdTBg',
    appId: '1:1047486986075:android:8db29713e2e33d871fcc7e',
    messagingSenderId: '1047486986075',
    projectId: 'flutterapps-1b0d5',
    storageBucket: 'flutterapps-1b0d5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJwPjrTEG6-awc_eP34-WefqOuIpXtY10',
    appId: '1:1047486986075:ios:14179a66ccdca1d91fcc7e',
    messagingSenderId: '1047486986075',
    projectId: 'flutterapps-1b0d5',
    storageBucket: 'flutterapps-1b0d5.appspot.com',
    iosClientId:
        '1047486986075-6h5qklcb67op3tjgst8phlvc37o0ickb.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJwPjrTEG6-awc_eP34-WefqOuIpXtY10',
    appId: '1:1047486986075:ios:14179a66ccdca1d91fcc7e',
    messagingSenderId: '1047486986075',
    projectId: 'flutterapps-1b0d5',
    storageBucket: 'flutterapps-1b0d5.appspot.com',
    iosClientId:
        '1047486986075-6h5qklcb67op3tjgst8phlvc37o0ickb.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceApp',
  );
}
