// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXmEhP4BEa6BfLXRNIpmZH6IiyA-hB9Lc',
    appId: '1:402516469184:web:820d3953b365030ffed425',
    messagingSenderId: '402516469184',
    projectId: 'test-09090',
    authDomain: 'test-09090.firebaseapp.com',
    storageBucket: 'test-09090.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRcSTMBsOBO5EBuKvbyBzM4_-WhsIqzmI',
    appId: '1:402516469184:android:890a5b8e3b273af4fed425',
    messagingSenderId: '402516469184',
    projectId: 'test-09090',
    storageBucket: 'test-09090.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5G6cLoMzQQY4GV35jZiUHMhWBwiEhNhA',
    appId: '1:402516469184:ios:e96d75500047f295fed425',
    messagingSenderId: '402516469184',
    projectId: 'test-09090',
    storageBucket: 'test-09090.appspot.com',
    iosClientId: '402516469184-rh446cu9p4fphdqv8p3h2o3h1ngep79p.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseApp',
  );
}
